import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Alert } from "./types";

export function exportAlertsPdf(alerts: Alert[], meta: { sector: string; author: string }) {
  const doc = new jsPDF();
  doc.setFontSize(18);
  doc.text("MineMesh — Alert Report", 14, 18);
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`Sector: ${meta.sector}`, 14, 26);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 31);
  doc.text(`Generated by: ${meta.author}`, 14, 36);

  autoTable(doc, {
    startY: 42,
    head: [
      ["Alert ID", "Worker", "Device", "Node", "Hazard", "Severity", "Time", "Ack By"],
    ],
    body: alerts.map((a) => [
      a.id,
      a.workerName,
      a.deviceId,
      a.nodeId,
      a.hazard,
      a.severity,
      new Date(a.time).toLocaleString(),
      a.acknowledgedBy ?? "-",
    ]),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [217, 119, 6] },
  });

  doc.save(`minemesh-alert-report-${Date.now()}.pdf`);
}

export function exportAlertsCsv(alerts: Alert[]) {
  const headers = [
    "Alert ID",
    "Worker",
    "Device",
    "Node",
    "Sector",
    "Hazard",
    "Severity",
    "State",
    "Time",
    "Temperature",
    "Humidity",
    "Methane",
    "CarbonMonoxide",
    "Oxygen",
    "AcknowledgedBy",
  ];
  const rows = alerts.map((a) => [
    a.id,
    a.workerName,
    a.deviceId,
    a.nodeId,
    a.sectorId,
    a.hazard,
    a.severity,
    a.state,
    new Date(a.time).toISOString(),
    a.readings.temperature,
    a.readings.humidity,
    a.readings.methane,
    a.readings.carbonMonoxide,
    a.readings.oxygen,
    a.acknowledgedBy ?? "",
  ]);
  const csv = [headers, ...rows]
    .map((r) => r.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(","))
    .join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `minemesh-alert-report-${Date.now()}.csv`;
  link.click();
  URL.revokeObjectURL(url);
}
