/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminSupervisorsRouteImport } from './routes/admin.supervisors'
import { Route as AdminSectorsRouteImport } from './routes/admin.sectors'
import { Route as AdminSectorsIndexRouteImport } from './routes/admin.sectors.index'
import { Route as AdminSectorsSectorIdRouteImport } from './routes/admin.sectors.$sectorId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupervisorsRoute = AdminSupervisorsRouteImport.update({
  id: '/supervisors',
  path: '/supervisors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectorsRoute = AdminSectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectorsIndexRoute = AdminSectorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSectorsRoute,
} as any)
const AdminSectorsSectorIdRoute = AdminSectorsSectorIdRouteImport.update({
  id: '/$sectorId',
  path: '/$sectorId',
  getParentRoute: () => AdminSectorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/sectors': typeof AdminSectorsRouteWithChildren
  '/admin/supervisors': typeof AdminSupervisorsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/sectors/$sectorId': typeof AdminSectorsSectorIdRoute
  '/admin/sectors/': typeof AdminSectorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/supervisors': typeof AdminSupervisorsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin': typeof AdminIndexRoute
  '/admin/sectors/$sectorId': typeof AdminSectorsSectorIdRoute
  '/admin/sectors': typeof AdminSectorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/sectors': typeof AdminSectorsRouteWithChildren
  '/admin/supervisors': typeof AdminSupervisorsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/sectors/$sectorId': typeof AdminSectorsSectorIdRoute
  '/admin/sectors/': typeof AdminSectorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/sectors'
    | '/admin/supervisors'
    | '/auth/login'
    | '/auth/signup'
    | '/admin/'
    | '/admin/sectors/$sectorId'
    | '/admin/sectors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/supervisors'
    | '/auth/login'
    | '/auth/signup'
    | '/admin'
    | '/admin/sectors/$sectorId'
    | '/admin/sectors'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/sectors'
    | '/admin/supervisors'
    | '/auth/login'
    | '/auth/signup'
    | '/admin/'
    | '/admin/sectors/$sectorId'
    | '/admin/sectors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/supervisors': {
      id: '/admin/supervisors'
      path: '/supervisors'
      fullPath: '/admin/supervisors'
      preLoaderRoute: typeof AdminSupervisorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sectors': {
      id: '/admin/sectors'
      path: '/sectors'
      fullPath: '/admin/sectors'
      preLoaderRoute: typeof AdminSectorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sectors/': {
      id: '/admin/sectors/'
      path: '/'
      fullPath: '/admin/sectors/'
      preLoaderRoute: typeof AdminSectorsIndexRouteImport
      parentRoute: typeof AdminSectorsRoute
    }
    '/admin/sectors/$sectorId': {
      id: '/admin/sectors/$sectorId'
      path: '/$sectorId'
      fullPath: '/admin/sectors/$sectorId'
      preLoaderRoute: typeof AdminSectorsSectorIdRouteImport
      parentRoute: typeof AdminSectorsRoute
    }
  }
}

interface AdminSectorsRouteChildren {
  AdminSectorsSectorIdRoute: typeof AdminSectorsSectorIdRoute
  AdminSectorsIndexRoute: typeof AdminSectorsIndexRoute
}

const AdminSectorsRouteChildren: AdminSectorsRouteChildren = {
  AdminSectorsSectorIdRoute: AdminSectorsSectorIdRoute,
  AdminSectorsIndexRoute: AdminSectorsIndexRoute,
}

const AdminSectorsRouteWithChildren = AdminSectorsRoute._addFileChildren(
  AdminSectorsRouteChildren,
)

interface AdminRouteChildren {
  AdminSectorsRoute: typeof AdminSectorsRouteWithChildren
  AdminSupervisorsRoute: typeof AdminSupervisorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSectorsRoute: AdminSectorsRouteWithChildren,
  AdminSupervisorsRoute: AdminSupervisorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
